loginPath:
    path:  /login
    defaults: { _controller: AppBundle:login:login }
    requirements:
        _method:  POST

getPosts:
    path:  /getposts
    defaults: { _controller: AppBundle:posts:getposts }
    requirements:
        _method:  POST

app:
    resource: '@AppBundle/Controller/'
    type: annotation


